"""
Agent 7: Report Generation Agent
Creates professional PDF reports using ReportLab
"""

import io
import os
from datetime import datetime
from typing import Dict, Any, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, Image, PageBreak, KeepTogether
)
from reportlab.platypus.flowables import Flowable
from reportlab.pdfgen import canvas
import pandas as pd


# ── Brand Colors ──────────────────────────────────────────────────
INDIGO = colors.HexColor("#6366f1")
DARK_BG = colors.HexColor("#0f0f14")
SURFACE = colors.HexColor("#1a1a24")
SURFACE2 = colors.HexColor("#22223a")
TEXT_PRIMARY = colors.HexColor("#e2e2f0")
TEXT_SECONDARY = colors.HexColor("#9090a8")
CYAN = colors.HexColor("#22d3ee")
AMBER = colors.HexColor("#f59e0b")
GREEN = colors.HexColor("#10b981")
RED = colors.HexColor("#ef4444")
WHITE = colors.white
LIGHT_GRAY = colors.HexColor("#2a2a3e")


def generate_pdf_report(
    profile: Dict[str, Any],
    qa_history: List[Dict],
    chart_images: List[bytes],
    executive_summary: str,
) -> bytes:
    """Generate a complete PDF report and return as bytes."""
    
    buffer = io.BytesIO()
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
    )
    
    styles = _build_styles()
    story = []
    
    # Cover Page
    story.extend(_cover_page(profile, styles))
    story.append(PageBreak())
    
    # Dataset Overview
    story.extend(_dataset_overview_section(profile, styles))
    story.append(Spacer(1, 12))
    
    # Executive Summary
    story.extend(_executive_summary_section(executive_summary, styles))
    story.append(PageBreak())
    
    # Analysis Results
    story.extend(_analysis_section(qa_history, chart_images, styles))
    
    # Footer note
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        f"Generated by InsightPilot AI • {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        styles["footer"]
    ))
    
    doc.build(story, onFirstPage=_add_background, onLaterPages=_add_background)
    
    return buffer.getvalue()


def _build_styles() -> Dict[str, ParagraphStyle]:
    """Build custom paragraph styles."""
    base = getSampleStyleSheet()
    
    return {
        "cover_title": ParagraphStyle(
            "CoverTitle",
            fontName="Helvetica-Bold",
            fontSize=32,
            textColor=WHITE,
            spaceAfter=8,
            alignment=TA_LEFT,
        ),
        "cover_subtitle": ParagraphStyle(
            "CoverSubtitle",
            fontName="Helvetica",
            fontSize=14,
            textColor=TEXT_SECONDARY,
            spaceAfter=6,
            alignment=TA_LEFT,
        ),
        "section_header": ParagraphStyle(
            "SectionHeader",
            fontName="Helvetica-Bold",
            fontSize=16,
            textColor=INDIGO,
            spaceBefore=14,
            spaceAfter=8,
            borderPadding=(0, 0, 4, 0),
        ),
        "subsection": ParagraphStyle(
            "Subsection",
            fontName="Helvetica-Bold",
            fontSize=12,
            textColor=CYAN,
            spaceBefore=10,
            spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "Body",
            fontName="Helvetica",
            fontSize=10,
            textColor=TEXT_PRIMARY,
            spaceAfter=6,
            leading=16,
        ),
        "muted": ParagraphStyle(
            "Muted",
            fontName="Helvetica",
            fontSize=9,
            textColor=TEXT_SECONDARY,
            spaceAfter=4,
            leading=14,
        ),
        "code": ParagraphStyle(
            "Code",
            fontName="Courier",
            fontSize=8.5,
            textColor=CYAN,
            backColor=SURFACE2,
            spaceBefore=4,
            spaceAfter=4,
            leftIndent=8,
            rightIndent=8,
            leading=13,
            borderPadding=(6, 6, 6, 6),
        ),
        "finding": ParagraphStyle(
            "Finding",
            fontName="Helvetica",
            fontSize=10,
            textColor=TEXT_PRIMARY,
            leftIndent=16,
            spaceBefore=3,
            spaceAfter=3,
            leading=15,
        ),
        "footer": ParagraphStyle(
            "Footer",
            fontName="Helvetica",
            fontSize=8,
            textColor=TEXT_SECONDARY,
            alignment=TA_CENTER,
        ),
    }


def _add_background(canvas_obj, doc):
    """Add dark background to every page."""
    canvas_obj.saveState()
    canvas_obj.setFillColor(DARK_BG)
    canvas_obj.rect(0, 0, A4[0], A4[1], fill=True, stroke=False)
    
    # Accent bar on left edge
    canvas_obj.setFillColor(INDIGO)
    canvas_obj.rect(0, 0, 4, A4[1], fill=True, stroke=False)
    
    # Header line
    canvas_obj.setStrokeColor(SURFACE)
    canvas_obj.setLineWidth(0.5)
    canvas_obj.line(20 * mm, A4[1] - 12 * mm, A4[0] - 20 * mm, A4[1] - 12 * mm)
    
    # Page number
    page_num = canvas_obj.getPageNumber()
    canvas_obj.setFillColor(TEXT_SECONDARY)
    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.drawCentredString(A4[0] / 2, 8 * mm, f"InsightPilot AI  ·  Page {page_num}")
    
    canvas_obj.restoreState()


def _cover_page(profile: Dict, styles: Dict) -> list:
    """Build the cover page elements."""
    story = []
    story.append(Spacer(1, 40))
    
    # Brand badge
    brand_data = [["⚡  InsightPilot AI"]]
    brand_table = Table(brand_data, colWidths=[120])
    brand_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), INDIGO),
        ("TEXTCOLOR", (0, 0), (-1, -1), WHITE),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 6),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [INDIGO]),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
    ]))
    story.append(brand_table)
    story.append(Spacer(1, 30))
    
    story.append(Paragraph("AI-Powered Data", styles["cover_subtitle"]))
    story.append(Paragraph("Analytics Report", styles["cover_title"]))
    story.append(Spacer(1, 16))
    
    story.append(HRFlowable(
        width="50%", thickness=2,
        color=INDIGO, spaceAfter=16
    ))
    
    # Dataset info
    story.append(Paragraph(
        f"Dataset: <b>{profile.get('filename', 'Unknown')}</b>",
        styles["cover_subtitle"]
    ))
    story.append(Paragraph(
        f"Type: {profile.get('dataset_type', 'Tabular Data')}",
        styles["cover_subtitle"]
    ))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%A, %B %d, %Y')}",
        styles["muted"]
    ))
    
    # Summary stats box
    story.append(Spacer(1, 40))
    stats_data = [
        ["Metric", "Value"],
        ["Total Records", f"{profile.get('rows', 0):,}"],
        ["Total Columns", str(profile.get('columns', 0))],
        ["Data Quality Score", f"{profile.get('quality_score', 0)}/100"],
        ["Missing Data", f"{profile.get('total_missing_pct', 0):.1f}%"],
        ["Dataset Type", profile.get('dataset_type', 'General')],
    ]
    
    stats_table = Table(stats_data, colWidths=[3 * inch, 2 * inch])
    stats_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), INDIGO),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("BACKGROUND", (0, 1), (-1, -1), SURFACE),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [SURFACE, LIGHT_GRAY]),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_PRIMARY),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 1), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, SURFACE2),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(stats_table)
    
    return story


def _dataset_overview_section(profile: Dict, styles: Dict) -> list:
    """Dataset overview with column breakdown."""
    story = []
    story.append(Paragraph("Dataset Overview", styles["section_header"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=SURFACE2, spaceAfter=8))
    
    # Column type breakdown
    col_profiles = profile.get("column_profiles", [])
    if col_profiles:
        story.append(Paragraph("Column Summary", styles["subsection"]))
        
        table_data = [["Column", "Type", "Missing", "Unique Values"]]
        for cp in col_profiles[:20]:  # Limit to first 20
            table_data.append([
                cp.get("name", ""),
                cp.get("type", ""),
                f"{cp.get('null_pct', 0):.1f}%",
                f"{cp.get('unique_count', 0):,}",
            ])
        
        col_table = Table(table_data, colWidths=[2.5 * inch, 1 * inch, 1 * inch, 1.2 * inch])
        col_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), SURFACE2),
            ("TEXTCOLOR", (0, 0), (-1, 0), CYAN),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [SURFACE, DARK_BG]),
            ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_PRIMARY),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("PADDING", (0, 0), (-1, -1), 6),
            ("GRID", (0, 0), (-1, -1), 0.3, SURFACE2),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(col_table)
    
    return story


def _executive_summary_section(summary: str, styles: Dict) -> list:
    """Executive summary section."""
    story = []
    story.append(Paragraph("Executive Summary", styles["section_header"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=SURFACE2, spaceAfter=8))
    
    if summary:
        for para in summary.split("\n\n"):
            if para.strip():
                story.append(Paragraph(para.strip(), styles["body"]))
                story.append(Spacer(1, 6))
    
    return story


def _analysis_section(qa_history: List[Dict], chart_images: List[bytes], styles: Dict) -> list:
    """Analysis Q&A with charts and insights."""
    story = []
    story.append(Paragraph("Analysis Results", styles["section_header"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=SURFACE2, spaceAfter=8))
    
    chart_idx = 0
    
    for i, qa in enumerate(qa_history, 1):
        question = qa.get("question", "")
        insight = qa.get("insight", {})
        code_info = qa.get("code_info", {})
        
        items = []
        
        # Question header
        items.append(Paragraph(f"Analysis {i}", styles["subsection"]))
        items.append(Paragraph(f"Question: {question}", styles["body"]))
        
        # Code/methodology
        if code_info.get("code"):
            items.append(Spacer(1, 4))
            items.append(Paragraph("Query / Code:", styles["muted"]))
            code_text = code_info["code"][:500]  # Truncate long code
            items.append(Paragraph(code_text.replace("\n", "<br/>"), styles["code"]))
        
        # Chart image
        if chart_idx < len(chart_images) and chart_images[chart_idx]:
            try:
                img_buf = io.BytesIO(chart_images[chart_idx])
                img = Image(img_buf, width=5.5 * inch, height=2.8 * inch)
                items.append(Spacer(1, 8))
                items.append(img)
                chart_idx += 1
            except Exception:
                chart_idx += 1
        
        # Insights
        if insight:
            items.append(Spacer(1, 8))
            items.append(Paragraph("Key Findings:", styles["muted"]))
            for finding in insight.get("key_findings", []):
                items.append(Paragraph(f"• {finding}", styles["finding"]))
            
            if insight.get("recommendation"):
                items.append(Spacer(1, 4))
                items.append(Paragraph(
                    f"💡 Recommendation: {insight['recommendation']}",
                    styles["body"]
                ))
        
        items.append(HRFlowable(width="100%", thickness=0.3, color=SURFACE2, spaceAfter=12))
        story.append(KeepTogether(items))
    
    return story